# Generated by Django 3.2.6 on 2021-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_blocks', models.PositiveIntegerField()),
                ('begin_row', models.PositiveIntegerField()),
                ('end_row', models.PositiveIntegerField()),
                ('begin_col', models.PositiveIntegerField()),
                ('end_col', models.PositiveIntegerField()),
            ],
        ),
    ]
