# Generated by Django 3.2.6 on 2021-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_API', '0002_auto_20210824_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockitem',
            name='data_string',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
